[nfs]
172.31.85.223 ansible_ssh_user='ec2-user'

[webservers]
172.31.89.202 ansible_ssh_user='ec2-user'
172.31.93.209 ansible_ssh_user='ec2-user'

[db]
172.31.80.152 ansible_ssh_user='ec2-user' 

[lb]
172.31.92.76 ansible_ssh_user='ubuntu'